### ISSUE TITLE
Undefined card fallback setting for slot ignored if resolve setting exists globally

### ISSUE THREAD

**Issue by ghost** [archfizz/slotmachine#12]
If a page is configured to resolve a request for undefined card by returning a default card, then this causes the setting for the resolving an undefined card specific to that slot to be ignored. 

```
options:
    resolve_undefined: DEFAULT_CARD

slots:
    image:
        key: a
        reel: image
        resolved_undefined: FALLBACK_CARD

reels:
    images:
        0: default.jpg
        1: one.jpg
        2: two.jpg
    aliases:
        _fallback: 2
```
